project:
  type: website

website:
  title: "Weather Insights"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - sources.qmd
      - data-analysis.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



